### ISSUE TITLE
Can you share the train/split of Gleason dataset?

### ISSUE THREAD

**Issue by hmchuong** [lxasqjc/Foveation-Segmentation#1]
Can you share the files: /data/train1_validation_gleason2019.odgt and ./data/val1_validation_gleason2019.odgt ?
Thank you

**Comment by lxasqjc** [comment]
Thanks for your interests, pls see the last commit as your request. Best

**Comment by lxasqjc** [comment]
> Can you share the files: /data/train1_validation_gleason2019.odgt and ./data/val1_validation_gleason2019.odgt ?
> Thank you

Thanks for your interests, pls see the last commit as your request. Best
